sudo: false
os: linux
language: haskell
before_install:
  - sudo apt-get -qq update && sudo apt-get install pandoc
addons:
  apt:
    packages:
      - texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended texlive-lang-french
# before_install:
    # - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended texlive-lang-french ghc haskell-platform
install:
    - cabal update
    - cabal install pandoc-crossref
    # - export CABALDIR=.cabal
    # - export PANDOC_CROSSREF=$CABALDIR/bin/
    # - export PATH=$PATH:$CABALDIR/bin
    # - ls $CABALDIR/bin
    - sudo pip install -U pip panflute pandocfilters  pandoc-numbering
cache:
    - pip
script:
    - make travis
# deploy:
#   provider: releases
#   api_key: "$GH_TOKEN"
#   file:
#     - "cours.pdf"
#   skip_cleanup: true
#   on:
#     tags: true
