matrix:
    include:
        - os: linux
          sudo: false
          language: r
          pandoc_version: 2.1
          before_install:
            apt:
              packages:
                - texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-french cabal  
          install:
              - pip install --user pandocfilters pandoc-numbering
              - cabal update
              - cabal install pandoc-crossref
          addons:
          
          cache:apt:
            packages:
              - texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-french cabal
          - packages
          - pip
script:
    - make 
# deploy:
#   provider: releases
#   api_key: "$GH_TOKEN"
#   file:
#     - "cours.pdf"
#   skip_cleanup: true
#   on:
#     tags: true
