sudo: false
dist: trusty
before_install:
  - sudo apt-get -qq update
addons:
  apt:
    packages:
      - texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended texlive-lang-french ghc haskell-platform
# before_install:
    # - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended texlive-lang-french ghc haskell-platform
install:
    - cabal update
    - cabal install pandoc pandoc-crossref
    - pip install -U pip pandocfilters  pandoc-numbering
cache:
    - pip
script:
    - make 
# deploy:
#   provider: releases
#   api_key: "$GH_TOKEN"
#   file:
#     - "cours.pdf"
#   skip_cleanup: true
#   on:
#     tags: true
